# Kompilator i flagi
CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17 -O2 -Iheaders

# Pliki źródłowe biblioteki
SRC = src/integral.cpp src/linear.cpp src/nonlinear.cpp src/interp.cpp src/ode.cpp src/numlib.cpp
OBJECTS = $(SRC:.cpp=.o)

# Domyślny cel
all: tests example_linear

# Cel: tests
tests: test/tests.o $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o tests test/tests.o $(OBJECTS)

test/tests.o: test/tests.cpp
	$(CXX) $(CXXFLAGS) -c test/tests.cpp -o test/tests.o

# Cel: example_linear
example_linear: examples/Example_Linear.o $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o example_linear examples/Example_Linear.o $(OBJECTS)

examples/Example_Linear.o: examples/Example_Linear.cpp
	$(CXX) $(CXXFLAGS) -c examples/Example_Linear.cpp -o examples/Example_Linear.o

# Czyszczenie
clean:
	rm -f $(OBJECTS) test/tests.o examples/Example_Linear.o tests example_linear
